services:
  - type: web
    name: audio-separation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "cleaner.backend.app:app"
    envVars:
      - key: PORT
        value: 10000
